#!/bin/sh
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
	echo "help message"
	exit 1
fi

TIADIR=$SCRIPTDIR/tia
PROFILE=$(cat $HOME/.config/profile)

RGX="^#@{0,2}[a-zA-ZščžŠČŽ0-9 \+\-]*$"

hkdscs=$(awk '/^#@@?[a-zA-ZščžŠČŽ0-9 \+\-]*$/{x=NR+1}(NR<=x){print}' "$HOME/.config/sxhkd/sxhkdrc_$PROFILE" | tr "@" "#")

dwmscs=$(awk '/^#@@?[a-zA-ZščžŠČŽ0-9 \+\-]*$/{x=NR+1}(NR<=x){print}' "$TIADIR/dwmshortcuts" | tr "@" "#")


echo "#It's not the end of the world..." > /tmp/tmpfile
echo "$dwmscs" >> /tmp/tmpfile
echo "$hkdscs" >> /tmp/tmpfile

markdown /tmp/tmpfile > /tmp/help.html
rm /tmp/tmpfile

chromium /tmp/help.html

exit 0
