#!/bin/sh

DATES="$SCRIPTDIR/calendar/importantdates"

TODAY="$(date +'%-d %-m %Y')"
DT=$(echo $TODAY | awk '{print $1}')
MT=$(echo $TODAY | awk '{print $2}')
YT=$(echo $TODAY | awk '{print $3}')

notifications=""

while read LINE; do

	if [ "$(echo $LINE | cut -c1)"	= "#" ]; then
		continue
	fi

	date=$( echo "$LINE" | cut -d',' -f1 | tr "." " " )
	typ=$( echo "$LINE" | cut -d',' -f2 )
	title=$( echo "$LINE" | cut -d',' -f3 )

	ddate=$(echo $date | awk '{print $1}')
	mdate=$(echo $date | awk '{print $2}')
	ydate=$(echo $date | awk '{print $3}')
	
	if [ "$ddate" = "E" ]; then
		ddate=$DT
	fi
	if [ "$mdate" = "E" ]; then
		mdate=$MT
	fi
	if [ "$ydate" = "E" ]; then
		ydate=$YT
	fi

	if [ "$DT" = "$ddate" ] && [ "$MT" = "$mdate" ] && [ "$YT" = "$ydate" ]; then
		notifications=$notifications"$title\n"
	fi

done < $DATES

echo $notifications

if [ ! "$notifications" = "" ]; then 
	$(echo "$notifications" | dmenu -p "As of today..." $(echo $DMENU_WHITE $DMENU_CENTER_TOP) -l $(( $(echo $notifications | wc -l) - 1))) > /dev/null
fi

exit 0
