#!/bin/sh
[ "$1" = "--help" ] && echo "help message" && exit 1

# if this file exists s/pdif is unmuted
CHANNEL="IEC958"
ALSAFILE="/tmp/alsacontrol"

if [ ! -f "$ALSAFILE" ]; then
	touch $ALSAFILE
	amixer sset $CHANNEL,0 unmute
	amixer sset 'Master',0 mute
else
	rm $ALSAFILE
	amixer sset $CHANNEL,0 mute
	amixer sset 'Master',0 unmute
fi
exit 0
