#!/bin/sh
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
	echo "help message"
	exit 1
fi

# if this file exists s/pdif is unmuted
CHANNEL="IEC958"
ALSAFILE="/tmp/alsacontrol"

if [ ! -f "$ALSAFILE" ]; then
	touch $ALSAFILE
	amixer sset $CHANNEL,0 unmute
	amixer sset 'Master',0 mute
else
	rm $ALSAFILE
	amixer sset $CHANNEL,0 mute
	amixer sset 'Master',0 unmute
fi
exit 0
