#!/bin/bash

g=$(tput setaf 2)
e=$(tput sgr0)

if [[ $# -eq 0 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
	echo -e "\nUsage:$g aura [git repo]$e\n"
	exit 1
fi

repo=$1

cd /opt
sudo git clone $repo

new=$(ls -td -- */ | head -n 1)

sudo chmod +777 $new

cd $new

makepkg -sri

exit 0
