#!/bin/bash
# Thank you, Luke Smith

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"
shebang=$(sed -n 1p "$file")

textype() { \
	cmd="pdflatex"
	$cmd --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	$cmd --output-directory="$dir" "$base" &&
	$cmd --output-directory="$dir" "$base"
}

cd "$dir" || exit

case "$file" in
	*\.tex) textype "$file" ;;
	*config.h) sudo make clean install ;;
	*) ;;
esac
