#!/bin/bash

opt1="Battery"
opt2="AC + compton"
opt3="AC - compton"

res=""

res=$(echo -e "$opt1\n$opt2\n$opt3" | dmenu -i -p "Power option: ")

if [ "$res" == "$opt1" ]; then
	pkill wallpaper
	wallpaper sf &
	pkill compton
	xbacklight -set 10 &
	sudo tlp bat &
elif [ "$res" == "$opt2" ]; then
	pkill wallpaper
	wallpaper &
	compton --config /home/anej/.config/compton.conf &
	xbacklight -set 100 &
	sudo tlp ac &
elif [ "$res" == "$opt3" ]; then
	pkill wallpaper
	wallpaper &
	pkill compton &
	xbacklight -set 100 & 
	sudo tlp ac &
fi
exit 0
