#!/bin/sh
COMMITNAME="Synchronisation"
FAKSDIR="$HOME/Documents/Faks"

echo "Syncing git repos."

if [ "$1" = "push" ]; then
	echo "Pushing HOME."
	cd $HOME
	git submodule update --remote --merge
	gc $COMMITNAME

elif [ "$1" = "pull" ]; then
	echo "Pulling HOME."
	cd $HOME
	git submodule update --remote --merge
	git pull origin master
else
	echo "Add push or pull argument!"
	exit 1
fi

echo "All done. Exiting."
exit 0
