#!/bin/bash

if [ $# -eq 0 ]; then
	ls *.pdf | entr pkill -HUP mupdf &
	mupdf *.pdf &
else
	file=$(readlink -f "$1")
	base="${file%.*}"
	echo "$base.pdf" | entr pkill -HUP mupdf &
	mupdf "$base.pdf" &
fi
